//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_PROJE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int User_ID { get; set; }
        public string Username { get; set; }
        public string User_Mail { get; set; }
        public string User_Password { get; set; }
    }
}
